apiVersion: v1
kind: Secret
metadata:
  name: bamboo-secret
  namespace: default
type: Opaque
data:
  displayName: VmljdG9yIE9zZWdoYWxl
  dpassword: cGFzc3dvcmQ=
  dusername: cG9zdGdyZXM=
  emailAddress: dm9zZWdoYWxlQGF0bGFzc2lhbi5jb20=
  license: QUFBQ0xnME9EQW9QZU5wMWsxRnpvakFVaGQvNUZablp0KzZnSUZiZHp2Q2drTFoyRlZ6QWRyZmJmUWg0bFZSSW1DUm8vZmNiVWFZZHUvdkFBOXljbSsrZWMvbVMxSUJpcUpEZFI3WnowKy9kOUlmSXczR0NlbGJQTnJad2VBUWhLV2V1UGJDc29UVnlITnRJU1pseTNwblJESmdFdktMcWVBQUhDWTRXMFRUR1JsQ1hLWWh3dlpSYTdKcTI0WEdtU0tZQ1VvSmI3dmxyUmlITCtWNXVhZHVzbFV5YTF4blBTREhlQUZPTi9IekdKNHA0K2hzSVY0a2FqRVV0c3B4STBOL0JQZkthbG1QYVBlTU1saHdxYUc3MDhTT2VoUXNjdFJYOFZsRnhhR1FMeHhuY3QzeDRUbWh4Q1JpRDJJR1krdTRFRDdIWjk1OTc1aUI4R0pwM3pyZFJTNmExZEFjbnFuOE9GRUhKRmJ4UFZKeEE3b25NM2JtMzkyNzk3VStIKzVNQm5rZHBjUGYyOVcwN0hqbWtXMi93MHpqLzhUeUw3VEI3eUovNis2ZjE5bnJFTTVyc3YxZkJjRGQrY1Y5Y0k2NVRtUWxhTlVIOG4ySlJFUGJSMEE5R2ZURHBjL0hDeGF1cnF5Qk16TnN3TWhkUjZDKzlaQm9HNWpMR3V1QjZBclN2SzVRZWtNb0JuYnNnekRLK0FvRXF3VjhoVStoM3JsVDFjdFB0YnJSN3FpQlNVc0k2R1MrN1oydE1PQ24rZEpEUEVlTUtyYWhVZ3FhMUF0MlpTcVE0eW1xcGVLbVhyR1BvNlBSbU1NS3l6L0ZxTGkvQzR3VDc1dVRYRWZJaTRqT2t6bmpKdG96dm1SSGp3TldQZVcxWlJpZzJoRkZKR25QSExTdWFIaGVSa2NKb0p0YTF5elU4RDlMK1FEM0RoL2VRV2wvMFJvQm9ERnR6b1h0S2hkbk93RHRTMUtjTDE2U1FZUHdGVWFZKzlUQXNBaFFHKzVGaGpCYTdJejk0UHFOYUFQeENpK2Y0YlFJVUpwU01SeVJVY0c3bEtnb29Rb3RDeGxNUjJLOD1YMDJxNg==
  password: cGFzc3dvcmQ=
  security-token: ZDNmNzlmMzY3ZDNmOTgzOWJhN2NmMzY3MWQxNGVmYTdhMDcwYTI0ZA==
  username: YWRtaW4=
