---
apiVersion: v1
kind: Namespace
metadata:
  name: haproxy-controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-configmap
  namespace: haproxy-controller
data:
  5432:
    default/postgres-svc:5432
  54663:
    default/bamboo-jms:54663
  ssl-certificate: 
    "cert-manager/cert-manager-webhook-ca"
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: haproxy
spec:
  controller: haproxy.org/ingress-controller