kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: default-workshop-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp2
  iopsPerGB: "50"
  encrypted: "true"